export const CONSTANTS = {
	GET_USERS 		: "GET_USERS",
	GET_REQUEST		: "GET_REQUEST",
	GET_SUCCESS 	: "GET_SUCCESS",
	GET_FAIL		: "GET_FAIL",

	DELETE_USER 	: "DELETE_USER",
	DELETE_REQUEST	: "DELETE_REQUEST",
	DELETE_SUCCESS 	: "DELETE_SUCCESS",
	DELETE_FAIL		: "DELETE_FAIL",

	REG_REQUEST		: "REG_REQUEST",
	REG_SUCCESS 	: "REG_SUCCESS",
	REG_FAIL		: "REG_FAIL",

// add user
	USER_FORM : "USER_FORM",

};

